### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by aniief** [qinzheng93/GeoTransformer#1]
```bash
$CUDA_VISIBLE_DEVICES=0 python trainval.py
```
```
[2022-02-27 23:30:57] [INFO] Epoch 1/40, iter 420/20642, loss: 2.751, c_loss: 0.987, f_loss: 1.764, PIR: 0.012, IR: 0.452, RRE: 5.354, RTE: 0.120, lr: 1.000e-04, time: 0.084s/0.273s
[2022-02-27 23:31:00] [ERRO] Error: CUDA out of memory. Tried to allocate 430.00 MiB (GPU 0; 10.76 GiB total capacity; 8.44 GiB already allocated; 247.44 MiB free; 9.41 GiB reserved in total by PyTorch)
```
 It occurs at iter 40 when i set the "config.train_num_worker” by 1 in the config.py, 420 when i set the "config.train_num_worker” by 8.
How to avoid it?
Thank you very much.

**Comment by qinzheng93** [comment]
GPU with 11GB memory is too small to train GeoTransformer. I use GTX 3090 in the experiments. You can possibly reduce the channels or the number of transformer layers.

**Comment by lemonade-lm** [comment]
> GPU with 11GB memory is too small to train GeoTransformer. I use GTX 3090 in the experiments. You can possibly reduce the channels or the number of transformer layers.

I have 48GB memory ,but it shows CUDA out of memory too, what amazes me is that it happens on epoch 2, i didn't change the any code. Why - _- ?

**Comment by mooncake199809** [comment]
> > GPU with 11GB memory is too small to train GeoTransformer. I use GTX 3090 in the experiments. You can possibly reduce the channels or the number of transformer layers.
> 
> I have 48GB memory ,but it shows CUDA out of memory too, what amazes me is that it happens on epoch 2, i didn't change the any code. Why - _- ?

Do you solve this problem?
