### ISSUE TITLE
The problem about the train loss can't converge

### ISSUE THREAD

**Issue by stepwhal** [qinzheng93/GeoTransformer#10]
Thank you for your work！I want to try to train your code. In the process of trying, I trained one scene data from the  3DMatch‘  preprocessed data, but after iterating many times, I found  the loss could not converge(exactly ，it has been stuck around 2.0), how did you deal with this problem? Or, have you encountered such a problem? thank you for your reply！

**Comment by rayguan97** [comment]
My training on 3DMatch also stuck around 2.0-1.9. How did you resolve it?
