### ISSUE TITLE
The inference output (estimated_transform) is related to gt_transform? 

### ISSUE THREAD

**Issue by dspeia** [qinzheng93/GeoTransformer#107]
Hi, qin zheng

It seems the inference output (estimated_transform) is related to input: gt_transform. 
As i know, the gt_transform just for calculate lose(RRE, RTE), right? i'm so confuse, thank for your any reply.

when i run below cmd from  [https://github.com/qinzheng93/GeoTransformer?tab=readme-ov-file#testing-on-your-own-data](url):
`CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../data/demo/src.npy --ref_file=../../data/demo/ref.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`

the gt is load from gt_file:
`gt transform:
[[ 0.95587096 -0.15354693  0.25032179  0.4314653 ]
 [ 0.17460698  0.98251641 -0.06408779  0.00941346]
 [-0.23611899  0.10497365  0.96600421  0.29711348]
 [ 0.          0.          0.          1.        ]]
`
the inference output estimated_transform:
`[[ 0.96041775  0.02890578  0.27706015  0.46721074]
 [-0.07060495  0.98738337  0.14173505 -0.48177984]
 [-0.26946762 -0.15568656  0.9503414   0.10626769]
 [ 0.          0.          0.          1.        ]]`

and the result is ok (attachment pic):
![Screenshot from 2024-05-14 19-09-53](https://github.com/qinzheng93/GeoTransformer/assets/72907719/8038dbc4-c922-4fbd-8f5c-32cc2276a9e7)

But when i change the gt transform to:
`transform = np.eye(4)`

the result become very bad:
`estimated_transform:
[[ 0.33815324 -0.7605605   0.55425644 -1.1210275 ]
 [ 0.8776755   0.04233276 -0.477382   -0.19036686]
 [ 0.33961478  0.6478856   0.6818402   0.8180617 ]
 [ 0.          0.          0.          1.        ]]
`
![Screenshot from 2024-05-14 19-12-19](https://github.com/qinzheng93/GeoTransformer/assets/72907719/348c8f34-18bc-4b41-ac5f-aab687081027)

related issues: #100 #95 #93

**Comment by dspeia** [comment]
After checking, the demo.py is run in training mode, need to switch to the eval mode by hand. Then finally get the correct estimated_transform on our dataset. thanks for qin zheng's awsome work.

**Comment by Doo77** [comment]
When using demo.py, I have already switched to evaluation mode, but the results for the provided test samples are very poor. Could you please tell me why this is happening?

![Image](https://github.com/user-attachments/assets/cef7d4e1-8212-493a-a4f6-9423b29860f0)

![Image](https://github.com/user-attachments/assets/27a76474-12c7-4416-bbb2-00cf5364f001)

**Comment by dspeia** [comment]
> When using demo.py, I have already switched to evaluation mode, but the results for the provided test samples are very poor. Could you please tell me why this is happening?
> 
> ![Image](https://github.com/user-attachments/assets/cef7d4e1-8212-493a-a4f6-9423b29860f0)
> 
> ![Image](https://github.com/user-attachments/assets/27a76474-12c7-4416-bbb2-00cf5364f001)


Hi, @Doo77 
please switch your "--src_file" and "--ref_file" on cmd, and try again.

**Comment by Doo77** [comment]
> > 使用 demo.py 时，我已经切换到评估模式，但提供的测试样本的结果非常差。你能告诉我为什么会发生这种情况吗？
> > ![Image](https://github.com/user-attachments/assets/cef7d4e1-8212-493a-a4f6-9423b29860f0)
> > ![Image](https://github.com/user-attachments/assets/27a76474-12c7-4416-bbb2-00cf5364f001)
> 
> 你好，[@Doo77](https://github.com/Doo77) 请在 cmd 上切换“--src_file”和“--ref_file”，然后重试。

Hi ，
I've switched my own data files, but it's also very poor

**Comment by Doo77** [comment]
> > 使用 demo.py 时，我已经切换到评估模式，但提供的测试样本的结果非常差。你能告诉我为什么会发生这种情况吗？
> > ![Image](https://github.com/user-attachments/assets/cef7d4e1-8212-493a-a4f6-9423b29860f0)
> > ![Image](https://github.com/user-attachments/assets/27a76474-12c7-4416-bbb2-00cf5364f001)
> 
> 你好，[@Doo77](https://github.com/Doo77) 请在 cmd 上切换“--src_file”和“--ref_file”，然后重试。

I don't know why, I haven't made any other changes to the demo.py, and the example given by the author doesn't work well for me.

**Comment by Doo77** [comment]
@dspeia Sorry, this is the first time I've asked a question on github, how does the test example given by the author work for you

**Comment by dspeia** [comment]
@Doo77  
I can get the correct register result by 3dmatch before, maybe there are mistakes in your command  (datafile or weight), 
so first, you need to reproduce the author's correct results based on the pure code & sample data (not switched to evaluation mode). if not, please connect the author：
`CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../data/demo/src.npy --ref_file=../../data/demo/ref.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`
