### ISSUE TITLE
Why is there no change in Registration RR when tested with 2500, 1000, 500, and 250 points respectively.

### ISSUE THREAD

**Issue by awordx** [qinzheng93/GeoTransformer#109]
Hello, first of all, thank you very much for your outstanding contribution. When reproducing your paper, I found that you used different numbers of points for testing, including 5000, 2500, 1000, 500, and 250. However, when selecting different points in the evaluation, the Registration RR metrics showed no variation, while other metrics did change. Could you please explain the reason for this?
![image](https://github.com/qinzheng93/GeoTransformer/assets/59833754/9ad5cdc0-03f3-4b45-a74f-6925cebf5b90)

**Comment by Wyyspace1203** [comment]
It seems that you have used   the lgr method, use rasanc instead

**Comment by awordx** [comment]
Oh, I understand now. Thank you very much
