### ISSUE TITLE
About the paper result

### ISSUE THREAD

**Issue by 35p32** [qinzheng93/GeoTransformer#11]
Hi bro! Thanks for your excellent work and  code. It is really an amazing paper and result
The paper result about Registration Recall was test by Ransac （Paper ,table1,bottom）
![1650703816(1)](https://user-images.githubusercontent.com/34885425/164887599-9d978475-92ae-487e-bf8a-1f9d8048ace7.png)

But when i use your pretrained model  and default ransac setting, I get the above result  which is strange 
![1650703943(1)](https://user-images.githubusercontent.com/34885425/164887669-e1cfffb0-3531-4fa4-ac94-6831b2b08d7e.png)

How does this  happen?  How to reproduce your result in table1?

**Comment by qinzheng93** [comment]
Change `_C.ransac.num_iterations' in [config.py](https://github.com/qinzheng93/GeoTransformer/blob/73e1439a7a61cced595b67712f70e472bcbf76a4/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/config.py#L65) to `50000`. That's the number used in the paper.

As there is randomness in RANSAC, the results can vary by +/- 2 points. It is normal.

**Comment by 35p32** [comment]
Got it  . Thanks a lot for your quick reply  and hope you have a good day.
