### ISSUE TITLE
Test and visualize on two given point clouds

### ISSUE THREAD

**Issue by ttsesm** [qinzheng93/GeoTransformer#12]
Hi, thanks for sharing your work. Is it easy to give some guidance or do you have any tutorial to test/evaluate the pre-trained models on two individual given point clouds?

**Comment by LinyeLi60** [comment]
> Hi, thanks for sharing your work. Is it easy to give some guidance or do you have any tutorial to test/evaluate the pre-trained models on two individual given point clouds?

Just write a new dataset

**Comment by ttsesm** [comment]
I've noticed that there is this [visualization script](https://github.com/qinzheng93/GeoTransformer/blob/main/geotransformer/utils/visualization.py) in the utils folder but I do not see to be used anywhere. 

> Just write a new dataset
>
Well isn't it a bit of overkill to write a new dataset class for testing on simple cases of two point clouds or something?

**Comment by LinyeLi60** [comment]
> 

Although it feels a bit like hitting mosquitoes with cannons, it's the easiest way to do it.🤭

**Comment by qinzheng93** [comment]
As @LinyeLi60 mentioned, the easiest way is to write a new dataset. This is because my code use `dict` to pass data across different modules, and KPConv has a complicated preprocessing (implemented [here](https://github.com/qinzheng93/GeoTransformer/blob/4ce888d6bcde2a6eb7ce8398112809a01e536bda/geotransformer/utils/data.py#L139)).

If you really don't to do this, you need to reorganize your data to contain the same keys as in my dataset, and call `registration_collate_fn_pack_mode` manually for KPConv preprocessing.

>I've noticed that there is this [visualization script](https://github.com/qinzheng93/GeoTransformer/blob/main/geotransformer/utils/visualization.py) in the utils folder but I do not see to be used anywhere.

Well there are just some helper functions to visualize correspondences and patch decomposition, you can simply call them in any of your code. And I provide more helper functions (here)[https://github.com/qinzheng93/GeoTransformer/blob/main/geotransformer/utils/open3d.py]. Hope they can help.

**Comment by ttsesm** [comment]
I see, thanks guys. I will try to see what I can do. @qinzheng93 ideally I was thinking a demo file similar to this one https://github.com/yewzijian/RegTR/blob/main/src/demo.py which is a comparable work yours.

Thanks.

**Comment by qinzheng93** [comment]
> I see, thanks guys. I will try to see what I can do. @qinzheng93 ideally I was thinking a demo file similar to this one https://github.com/yewzijian/RegTR/blob/main/src/demo.py which is a comparable work yours.
> 
> Thanks.

I add a simple demo script [here](https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py). Hope this can help.

**Comment by ttsesm** [comment]
Perfect, thanks a lot. 

Btw, could you give a feedback regarding how Geotransformer compares with [RegTR](https://github.com/yewzijian/RegTR), [Lepard](https://github.com/rabbityl/lepard) and [NgeNet](https://github.com/zhulf0804/NgeNet). All four works look quite nice and I am interested to see their differences. For sure one common part is that all relying on extracting keypoint features based on KPCONV (or variations of it).

**Comment by qinzheng93** [comment]
Yes all the four works use KPConv-based backbone. And they all use transformer to learn the global correlation. But they differ in the overall pipeline and in the motivation.

The idea of [RegTR](https://github.com/yewzijian/RegTR) comes from [COTR](https://github.com/ubc-vision/COTR) which directly regresses the coordinates of the corresponding points using transformer. [NgeNet](https://github.com/zhulf0804/NgeNet) is an extension to [PREDATOR](https://github.com/prs-eth/OverlapPredator) which leverages multi-level features and multi-scale voting. And [Lepard](https://github.com/rabbityl/lepard) utilizes a coarse-to-fine *registration* pipeline, where a coarse transformation is first estimated with weighted Procrutes and the final transformation is computed by RANSAC. The idea of GeoTransformer is from [LoFTR](https://github.com/zju3dv/LoFTR) and [CoFiNet](https://github.com/haoyu94/Coarse-to-fine-correspondences), where a coarse-to-fine *matching* strategy is adopted. As stated in our paper, coarse-to-fine pipelines can avoid detecting repeatable keypoints and thus extract better correspondences.

All the four works explore how to effectively embed geometric structures of the point clouds. RegTR uses absolute coordinate embedding, NgeNet uses a fused embedding with coordinates and PPF, Lepard uses a rotary embedding, and GeoTransformer uses a transformation-invariant geometric structure embedding. Some comparison of different embedding methods is shown in our paper.

To estimate the transformation, RegTR and GeoTransformer are RANSAC-free, while NgeNet and Lepard rely on RANSAC. And GeoTransformer reports the best performance among the four works.

Anyway, I think they are all very good works for point cloud registration.

**Comment by qinzheng93** [comment]
You are welcome :)
