### ISSUE TITLE
Question about downsample point cloud 

### ISSUE THREAD

**Issue by LinyeLi60** [qinzheng93/GeoTransformer#14]
Hi qinzheng, you mentioned that `you should scale your data to match the voxel size in 3DMatch (2.5cm)`, I am not  familiar with point cloud registation, so I use  `open3d.geometry.PointCloud.voxel_down_sample(2.5)`, is this correct? Thank you.

**Comment by qinzheng93** [comment]
Yes, but take care of the unit used. If the unit is meter (which is the most common case), use `open3d.geometry.PointCloud.voxel_down_sample(0.025)` to downsample the point cloud. You can also use [this method](https://github.com/qinzheng93/GeoTransformer/blob/2232c06e294e5bb4ddcb939331a0824a31c8d7b9/geotransformer/utils/open3d.py#L57) which is a easy-to-use wrapper.

If the results are not good, try to match the density of your own data and 3DMatch. A possible way is to scale the point cloud to match the `acceptance_radius` with 3DMatch (10cm). For example, if the correspondences closer than 10m after alignment are considered as inliers in your case, the point clouds could be scaled by a factor of 0.01.

**Comment by LinyeLi60** [comment]
> Yes, but take care of the unit used. If the unit is meter (which is the most common case), use `open3d.geometry.PointCloud.voxel_down_sample(0.025)` to downsample the point cloud. You can also use [this method](https://github.com/qinzheng93/GeoTransformer/blob/2232c06e294e5bb4ddcb939331a0824a31c8d7b9/geotransformer/utils/open3d.py#L57) which is a easy-to-use wrapper.
> 
> If the results are not good, try to match the density of your own data and 3DMatch. A possible way is to scale the point cloud to match the `acceptance_radius` with 3DMatch (10cm). For example, if the correspondences closer than 10m after alignment are considered as inliers in your case, the point clouds could be scaled by a factor of 0.01.

Thank you for your detail reply,  I use open3d.geometry.PointCloud.voxel_down_sample(0.025) and the result is nice. 

Closed.
