### ISSUE TITLE
Questions about running demo.py: voxel_size

### ISSUE THREAD

**Issue by ljjTYJR** [qinzheng93/GeoTransformer#16]
Hello @qinzheng93,

I pulled the latest code and try to run the code of [demo.py](https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py).

I wonder whether do I need to rescale the input point cloud again to make it similar to 3D-Match? 
(Since I observed that in the _demo.py_, there is a function :)
```
data_dict = registration_collate_fn_stack_mode(
        [data_dict], cfg.backbone.num_stages, cfg.backbone.init_voxel_size, cfg.backbone.init_radius, neighbor_limits
    )
```

I don't know how it works, does it function as rescaling the point cloud?

Thanks for your relpy.

**Comment by ljjTYJR** [comment]
And **Another question**:

If I want to use the pre-trained model on the outdoors scene, (similar to KITTI), should I downsample and rescale the input point cloud?
And what is the number limit of the input point and size?

**Comment by qinzheng93** [comment]
>I wonder whether do I need to rescale the input point cloud again to make it similar to 3D-Match?

If your data is significantly different from 3DMatch in density or you use a different acceptance radius for inlier correspondences, you could consider rescaling the point clouds. A possible way is to scale the point cloud to match the acceptance_radius with 3DMatch (10cm). For example, if the correspondences closer than 10m after alignment are considered as inliers in your case, the point clouds could be scaled by a factor of 0.01. And you should voxelize the point cloud with 2.5cm if your point cloud is very large (>>30000 points).

>The function of `registration_collate_fn_stack_mode`.

It is a data preprocessing used by KPConv. It downsamples the point clouds by grid subsampling and query the neighbors for each point by radius search. In most cases, you could ignore it.

>If I want to use the pre-trained model on the outdoors scene, (similar to KITTI), should I downsample and rescale the input point cloud?

For outdoor scenes, as different datasets could differ *greatly* in density and resolution, I don't know if it is reasonable to use pre-trained model from another dataset. You can give it a try.

>And what is the number limit of the input point and size?

I use ~30000 points on 3DMatch. As mentioned in the limitation section of the paper, the memory footprint is largely determined by the number of superpoints. So tune the number of backbone stages to avoid huge memory usage. For example, I use 3 stages on ModelNet40, 4 stages on 3DMatch but 5 stages on KITTI as the point clouds in KITTI are much larger.
