### ISSUE TITLE
3dMatch data file format error

### ISSUE THREAD

**Issue by WinterCodeForEverything** [qinzheng93/GeoTransformer#2]
I unzip 3dMatch from PREDATOR to get the following file format:
--rgbd-scenes-v2-scene_01
  --fragments/*.ply
  --poses/*.txt
So how can I change it to :
--rgbd-scenes-v2-scene_01
  *.pth

**Comment by qinzheng93** [comment]
You should use the preprocessed data from PREDATOR and you can download it using the following command:
```bash
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/data.zip
```
I don't know if PREDATOR has changed the data in the link. To generate the pth files from the ply files, you can manually downsample the point clouds with a voxel size of 2.5cm using open3d.

**Comment by WinterCodeForEverything** [comment]
Thanks, I have downloaded the raw data, but should download  the preprocessed data.

**Comment by CloudMW** [comment]
right
