### ISSUE TITLE
About KITTI Metadata, does the 'transform' already refined by ICP as claimed in paper? 

### ISSUE THREAD

**Issue by AAUfoa** [qinzheng93/GeoTransformer#20]
Thank you for share the metadata on KITTI.

As claimed in Section 4.2 Dataset "the ground-truth poses are refined with ICP", I want to confirm whether the 'transform' in metadata you provided in "data/Kitti/metadata"  have been refined with ICP? Or do I need to add ICP after reading in the metadata? 

Thank you !

**Comment by qinzheng93** [comment]
Yes, the transform in the metadata is the final one refined by ICP.
