### ISSUE TITLE
Create own model

### ISSUE THREAD

**Issue by zeroStrong** [qinzheng93/GeoTransformer#21]
Hi, thanks for sharing your work. 
I have a question.

I am trying to build a model with my own training data.
However, the number of training data is only about 100.
KITTI and 3DMatch have a huge number of training data. Is this number of data sufficient to show results?

**Comment by qinzheng93** [comment]
In fact, registration does not require too much data as it is a relatively low-level task. However, if the dataset is too small, the model may not see sufficient geometric structures. You can have a try, but I do not know though.
