### ISSUE TITLE
Unable to find/download 3DMatch dataset's metadata [help wanted]

### ISSUE THREAD

**Issue by barvin04** [qinzheng93/GeoTransformer#23]
Hello, 
    Thanks for the code. I followed the direction in 'GeoTransformer' and in 'OverlapPredator' to download the 3DMatch dataset. I cannot find the **metadata** for 3DMatch. Can you(/someone) kindly _share_ the metadata for it, or point me to where I may download it. 

Thanks!

**Comment by PANFEI-CHENG** [comment]
I have the same question.Have you solved it?
best wishes!

**Comment by PANFEI-CHENG** [comment]
可以下载OverlapPredator代码，然后sh scripts/download_data_weight.sh下载处理后的数据
或者
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/pairwise_reg/3dmatch.zip
unzip 3dmatch.zip直接下载原始数据。

**Comment by qinzheng93** [comment]
It is in `data/3DMatch/metadata`. Refer to the README for details.

**Comment by barvin04** [comment]
Thank you!
