### ISSUE TITLE
How to group data sets after downloading

### ISSUE THREAD

**Issue by yangsihai97** [qinzheng93/GeoTransformer#26]
Hello, author:
         I ran the python files in the Kitti dataset and ModelNet dataset folders according to your requirements, but they did not work and were not classified into the ones you described. Is there a specific method? thank you!

**Comment by qinzheng93** [comment]
Did you organize the data as described in the README?

**Comment by yangsihai97** [comment]
Yes, I did, but I reported many errors when running the categorizer of Kitti and modelnet datasets. Do you mean to organize data manually?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinzheng93/GeoTransformer] How to group data sets after downloading (Issue #26)






您是否按照 READ ME 中描述的方式组织数据？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by yangsihai97** [comment]
Sorry to bother you again. We ran the Kitti script without any effect, and then the modelnet script reported an error after running. Thank you for your answer!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinzheng93/GeoTransformer] How to group data sets after downloading (Issue #26)






是的，你需要把数据文件数据/基准然后运行脚本。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by qinzheng93** [comment]
What error do you have? And did you follow the README to put the downloaded data in `data/kitti` and `data/modelnet`?

**Comment by yangsihai97** [comment]
***@***.***，我做了一个我的问题描述汇总的文件，这里发送不了，可以麻烦您向我的邮箱发送一句话吧，这样我就可以通过邮箱把文件发给您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 晚上11:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinzheng93/GeoTransformer] How to group data sets after downloading (Issue #26)





 
What error do you have? And did you follow the README to put the downloaded data in data/kitti and data/modelnet?

**Comment by yangsihai97** [comment]
是q的youxiang，2659471523

**Comment by qinzheng93** [comment]
Could you show me how you put data in the data directory?

**Comment by yangsihai97** [comment]
Hello, I made a document (is the description in Chinese OK?) To describe my problems in detail, but the comments can't be sent. How can I send them to you?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2022年7月29日(星期五) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinzheng93/GeoTransformer] How to group data sets after downloading (Issue #26)





 
Could you show me how you put data in the data directory?
