### ISSUE TITLE
How to draw the point cloud like this ?

### ISSUE THREAD

**Issue by vision507** [qinzheng93/GeoTransformer#28]
Hi , thanks for your great work.
And I would like to know how can I get this kind of visualization result  in your paper.
![屏幕截图 2022-08-04 081115](https://user-images.githubusercontent.com/110574938/182736300-92826739-b725-482d-9ad6-e741d233027f.jpg)
When I  use open3d to draw the point clouds , it seems very ugly, so I'm  wondering how can I  get  your  visualization result. It would be very grateful.

**Comment by qinzheng93** [comment]
The figures are generated with open3d. Run `estimate_normals` before `draw_geometries`.

**Comment by vision507** [comment]
I  run estimate_normals before draw_geometries , but  the visualization still seems  not good ,  while  my point clouds  is very sparse ,  however  your visualization is  very  dense and tight ,  it your  point couds  visulized as  mesh?

**Comment by qinzheng93** [comment]
No, I simply use the 2.5cm downsampled point clouds for visualization. What data do you use?

**Comment by vision507** [comment]
But  my  open3d visualizatioin  result is  like this which I think  is far from good.
![image](https://user-images.githubusercontent.com/110574938/182820990-dd6324ad-e425-4b2b-9f3f-e17ec010f9eb.png)

**Comment by vision507** [comment]
Have you  used this function to visualize the  point clouds?
https://github.com/qinzheng93/GeoTransformer/blob/24fd5daa38985ec97fbb2fc8e5152c93c6814e8e/geotransformer/utils/visualization.py#L80

**Comment by qinzheng93** [comment]
> But my open3d visualizatioin result is like this which I think is far from good.
> ![image](https://user-images.githubusercontent.com/110574938/182820990-dd6324ad-e425-4b2b-9f3f-e17ec010f9eb.png)

This result is quite good. If you use a denser point cloud, the result will be similar with ours.

**Comment by qinzheng93** [comment]
> Have you used this function to visualize the point clouds?
> 
> https://github.com/qinzheng93/GeoTransformer/blob/24fd5daa38985ec97fbb2fc8e5152c93c6814e8e/geotransformer/utils/visualization.py#L80

This is used in the teaser.

**Comment by vision507** [comment]
> > But my open3d visualizatioin result is like this which I think is far from good.
> > ![image](https://user-images.githubusercontent.com/110574938/182820990-dd6324ad-e425-4b2b-9f3f-e17ec010f9eb.png)
> 
> This result is quite good. If you use a denser point cloud, the result will be similar with ours.

So how to  generate  a  dense  point cloud , should I  upsample the point clouds?

**Comment by qinzheng93** [comment]
> > > But my open3d visualizatioin result is like this which I think is far from good.
> > > ![image](https://user-images.githubusercontent.com/110574938/182820990-dd6324ad-e425-4b2b-9f3f-e17ec010f9eb.png)
> > 
> > 
> > This result is quite good. If you use a denser point cloud, the result will be similar with ours.
> 
> So how to generate a dense point cloud , should I upsample the point clouds?

It seems you directly visualize the RGB-D frame, right? You could follow 3DMatch to fuse consecutive 50 frames to get a dense point cloud.
