### ISSUE TITLE
About unseen objects

### ISSUE THREAD

**Issue by LinyeLi60** [qinzheng93/GeoTransformer#3]
Hi Zheng Qin, congratulations on your paper being accepted by CVPR. I am a novice in 3D vision,  I want to know that the pretrained model can be used directly on unseen point cloud?
![微信图片_20220308145312](https://user-images.githubusercontent.com/34992187/157183064-e3bac999-f945-4c68-952f-edce13d184b4.jpg)

**Comment by qinzheng93** [comment]
Yes. Actually, the point clouds in 3DMatch test scenes are unseen during training. However, density and precision problems are expected if you are testing it on point clouds from KITTI or ModelNet.

For example, the point clouds in 3DMatch usually covers a area of 3mx3m, while the point clouds in KITTI are much larger. And the point clouds in ModelNet are much smaller (1024 points v.s. ~30k points in 3DMatch).
