### ISSUE TITLE
How to create the .pkl file?

### ISSUE THREAD

**Issue by xiakunwonder** [qinzheng93/GeoTransformer#30]
Thank you for sharing the code.
test.pkl、train.pkl、val.pkl exist under the file: /geotransformer/data/Kitti/metadata . How can I make these files for my own datasets？

**Comment by xieKKKi** [comment]
> 

How did you solve this problem？

**Comment by xieKKKi** [comment]
> Thank you for sharing the code. test.pkl、train.pkl、val.pkl exist under the file: /geotransformer/data/Kitti/metadata . How can I make these files for my own datasets？

How did you solve this problem？

**Comment by suyuzhu** [comment]
How did you solve this problem？Thanks!
