### ISSUE TITLE
Some questions about neighbor_limits of registration_collate_fn_stack_mode method

### ISSUE THREAD

**Issue by zxkxdxx** [qinzheng93/GeoTransformer#32]
Hi,

Really appreciate releasing your amazing work! I have some questions regarding neighbor_limits of registration_collate_fn_stack_mode method. I see that in "demo. Py", the neighborhood_limits are set to [38, 36, 36, 38] (# default setting in 3dpatch) for registration_ collate_ fn_ stack_ mode method。 What I want to know is what does neighborhood_limits mean? If the laser radar data collected by yourself is put into demo.py, how should this neighborhood_limits be set?
![a1b48cae44c4a13baed90c5cc9c733e](https://user-images.githubusercontent.com/100589139/187165795-f65e06e6-11c6-4c84-acc9-58995623c9db.jpg)

**Comment by qinzheng93** [comment]
1. `neighborhood_limits` is the number of neighbors for each point in the computation of KPConv. It is determined by `radius_neighbor` function. See #31 .
2. For LiDAR data, you can try the settings in KITTI. I forget the exact numbers, but you can run the KITTI model to get it.
