### ISSUE TITLE
How much data is needed to train my own model

### ISSUE THREAD

**Issue by civilServant-666** [qinzheng93/GeoTransformer#34]
Hey, thank you for sharing your wonderful work!

I am trying to train the model with my own data. I wonder how much data I would need to get a decent performance (say, how many pairs of src.npy, ref.npy, and gt.npy)?

Thanks in advance!

**Comment by qinzheng93** [comment]
It is hard to say. I suppose it depends on how large the rotation is in your scene. 3DMatch has 20k training pairs, while KITTI only has 1400+.

**Comment by civilServant-666** [comment]
> It is hard to say. I suppose it depends on how large the rotation is in your scene. 3DMatch has 20k training pairs, while KITTI only has 1400+.

Thanks for the reply. I wonder how large a scenario should each training pair represents? Say, 3 m * 3 m?

**Comment by qinzheng93** [comment]
> 

The best way is to use all points. If you use a fixed size, the overlap could be small.

**Comment by lcxiha** [comment]
Hello, if I train the model with my own dataset, the dataset needs the  rotation matrix, translation matrix and the overlap rate of two-point cloud. Do I need other conditions besides these?Looking forward to your reply.

**Comment by joker-lb7** [comment]
> Hello, if I train the model with my own dataset, the dataset needs the rotation matrix, translation matrix and the overlap rate of two-point cloud. Do I need other conditions besides these?Looking forward to your reply.

I have a similar problem, I don't know how to calculate the overlap rate of homemade datasets, can you help? Thank you

**Comment by qinzheng93** [comment]
You can ignore the overlap ratio, but the transformation matrix is needed. You can use this [function](https://github.com/qinzheng93/GeoTransformer/blob/e7a135af4c318ff3b8d7f6c963df094d7e4ea540/geotransformer/utils/registration.py#L149C5-L149C5) to compute the overlap.

**Comment by joker-lb7** [comment]
> You can ignore the overlap ratio, but the transformation matrix is needed. You can use this [function](https://github.com/qinzheng93/GeoTransformer/blob/e7a135af4c318ff3b8d7f6c963df094d7e4ea540/geotransformer/utils/registration.py#L149C5-L149C5) to compute the overlap.

Are there two options: do not provide overlap.pkl or use the function you provided to calculate the overlap rate to generate overlap.pkl?
thanks

**Comment by qinzheng93** [comment]
> Are there two options: do not provide overlap.pkl or use the function you provided to calculate the overlap rate to generate overlap.pkl? thanks

It is okay to give a random overlap ratio value. It is only used for logging.

**Comment by joker-lb7** [comment]
> > Are there two options: do not provide overlap.pkl or use the function you provided to calculate the overlap rate to generate overlap.pkl? thanks
> 
> It is okay to give a random overlap ratio value. It is only used for logging.

This means I can randomly generate the overlap.pkl file according to the number of my dataset?thanks！
