### ISSUE TITLE
【demo.py】Change the input ground truth, the estimated transformation will change

### ISSUE THREAD

**Issue by ljjTYJR** [qinzheng93/GeoTransformer#37]
Hello,

When I was using 3d-match demo, I met with a strange thing:

I was testing the demo file:

[【3D-Match demo】](https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py)

It needs four inputs:
- The `src`
- The `ref`
- The `gt` (Ground Truth)
- The weights

But when I changed the `gt` input, the `estimated transformation` also changed.
In my view, the output (the `estimated transformation`) should be the same no matter what `gt` I provide.

where am I going wrong? Or is it the usual thing?

Best,
Shuo.

**Comment by ljjTYJR** [comment]
Found the wrong place:

If to use pre-trained data on my own test data, the `self. training` should be set `false`

**Comment by superstrong123** [comment]
> Found the wrong place:
> 
> If to use pre-trained data on my own test data, the `self. training` should be set `false`

我也有类似的问题，但是这个self.training我没找到，楼主在哪个文件找到这个参数的呢0.o？

**Comment by ljjTYJR** [comment]
> > Found the wrong place:
> > If to use pre-trained data on my own test data, the `self. training` should be set `false`
> 
> 我也有类似的问题，但是这个self.training我没找到，楼主在哪个文件找到这个参数的呢0.o？

[https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py
line 163](https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py#:~:text=correspondences%20during%20training-,if%20self.training%3A,-ref_node_corr_indices%2C%20src_node_corr_indices)

顺着模型的逻辑看下去就可以找到。
