### ISSUE TITLE
Questions about RANSAC

### ISSUE THREAD

**Issue by jinhong-ni** [qinzheng93/GeoTransformer#39]
Dear authors,

Thanks for open-sourcing your amazing work. I'm experimenting with RANSAC and I noticed some unexpected results compared to the paper. 

What I've done is first change the number of iterations in RANSAC to 50k. The evaluation runs extremely slowly (approx. 16 hrs in contrast to about 1 hr for local to global), and I only got performance similar to local to global. I also tried to change the number of points in RANSAC to a larger number (by default it is set to 3), such as 250, 500, 1000, etc. I did not achieve a significant gain in performance, even the recall collapses to zero if the number of points is set too big (like 5k). This is contradicting to what's reported in the paper, as the performance is reported to keep improving as the number of samples increases.

I would be super grateful if you could guide me through what I've done wrong here. Thanks in advance for your patience and help!

**Comment by qinzheng93** [comment]
One of the main contributions of our paper is accurate and fast RANSAC-free registration. So yes, RANSAC-50k is extremely slow, but the performance is similar with our LGR. This is expected.

Feeding RANSAC with more correspondences contributes to better results. It should not collapse with 5K correspondences. How did you run RANSAC? The `eval.py` has already provided RANSAC evaluation. Try the following command:
```bash
CUDA_VISIBLE_DEVICES=0 python eval.py --benchmark=3DMatch --method=ransac --num_corr=5000
```

**Comment by jinhong-ni** [comment]
Thanks! What I've done was changing `_C.ransac.num_points` in config. I will try the command to reproduce the results.

**Comment by qinzheng93** [comment]
> Thanks! What I've done was changing `_C.ransac.num_points` in config. I will try the command to reproduce the results.

`_C.ransac.num_points` is the number of points used to compute a transformation hypothesis (in a RANSAC step), typically it should be 3 or 4.

**Comment by jinhong-ni** [comment]
Thanks! That clarifies all my concerns.
