### ISSUE TITLE
Test on custom data

### ISSUE THREAD

**Issue by LinyeLi60** [qinzheng93/GeoTransformer#4]
Hi Qin Zheng, I want to known how to test the pretrained model on my own point cloud, can you give me some help or guidance? Thank you!

**Comment by qinzheng93** [comment]
Please refer to [the dataset file](https://github.com/qinzheng93/GeoTransformer/blob/main/geotransformer/datasets/registration/threedmatch_kpconv.py) and write a new `Dataset` class and a new `collate_fn` for your own point clouds. The `collate_fn` will preprocess the point clouds for KPConv.

To match the settings in 3DMatch, your own data should have a similar size and density with 3DMatch, i.e., ~30000 points and downsampled with a voxel size of 2.5cm.

**Comment by LinyeLi60** [comment]
Can I use the neighborhood_limits calibrated from `3DMatch` applied to my own point cloud?  I don't known how to  calculate neighborhood_limits on my own dataset.

**Comment by LinyeLi60** [comment]
Thank you, I have test GeoTransformer on my own data, the result is very good!

**Comment by qinzheng93** [comment]
> Thank you, I have test GeoTransformer on my own data, the result is very good!

That's great 👍 !

**Comment by LinyeLi60** [comment]
> @LinyeLi60 I am also interested testing on custom data. Could you give a bit more details how did you manage to finally do it in your case. Thanks.

Write a new dataset like ThreeDMatchPairKPConvDataset, then every thing will be fine.

**Comment by ttsesm** [comment]
you mean something similar to this class https://github.com/qinzheng93/GeoTransformer/blob/4ce888d6bcde2a6eb7ce8398112809a01e536bda/geotransformer/datasets/registration/threedmatch/dataset.py#L18

**Comment by LinyeLi60** [comment]
Yes





------------------ Original ------------------
From: ttsesm ***@***.***&gt;
Date: Fri,May 6,2022 9:36 PM
To: qinzheng93/GeoTransformer ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [qinzheng93/GeoTransformer] Test on custom data (Issue #4)

**Comment by qinzheng93** [comment]
> you mean something similar to this class
> 
> https://github.com/qinzheng93/GeoTransformer/blob/4ce888d6bcde2a6eb7ce8398112809a01e536bda/geotransformer/datasets/registration/threedmatch/dataset.py#L18

To match the settings in 3DMatch, your own data should have a similar size and density with 3DMatch, i.e., ~30000 points and downsampled with a voxel size of 2.5cm. Just simply rescaling according to your precision requirement should work fine.

**Comment by cp3cp** [comment]
> Thank you, I have test GeoTransformer on my own data, the result is very good!
I wonder which pretrain model do you use? thanks

**Comment by dspeia** [comment]
Hi, qin zheng

Thanks for your work. i tested your demo.py as 
https://github.com/qinzheng93/GeoTransformer?tab=readme-ov-file#testing-on-your-own-data, the result is good.
`CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../data/demo/src.npy --ref_file=../../data/demo/ref.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`

and i got very bad visualization result when use (attachment pic):
`CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../3dmatch/test/7-scenes-redkitchen_npy/cloud_bin_2.npy  --ref_file=../../3dmatch/test/7-scenes-redkitchen_npy/cloud_bin_3.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`

the src_file, ref_file is  down_sample and save to npy from 3dmatch test-set(test/7-scenes-redkitchen):
` voxel_down_pcd = pcd_data.voxel_down_sample(voxel_size=0.025)`
   
i'm so confuse about this result, would you please tell me which ply file on 3dmatch is your data/demo/src.npy & dts.npy, 
and is my preprocess is correct (read ply->downsample->save npy)? 
![Screenshot from 2024-05-13 17-59-38](https://github.com/qinzheng93/GeoTransformer/assets/72907719/841a8e19-6c99-4dec-9c24-9f9de1adfbf3)

**Comment by dspeia** [comment]
> Hi, qin zheng
> 
> Thanks for your work. i tested your demo.py as https://github.com/qinzheng93/GeoTransformer?tab=readme-ov-file#testing-on-your-own-data, the result is good. `CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../data/demo/src.npy --ref_file=../../data/demo/ref.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`
> 
> and i got very bad visualization result when use (attachment pic): `CUDA_VISIBLE_DEVICES=0 python demo.py --src_file=../../3dmatch/test/7-scenes-redkitchen_npy/cloud_bin_2.npy --ref_file=../../3dmatch/test/7-scenes-redkitchen_npy/cloud_bin_3.npy --gt_file=../../data/demo/gt.npy --weights=../../weights/geotransformer-3dmatch.pth.tar`
> 
> the src_file, ref_file is down_sample and save to npy from 3dmatch test-set(test/7-scenes-redkitchen): ` voxel_down_pcd = pcd_data.voxel_down_sample(voxel_size=0.025)`
> 
> i'm so confuse about this result, would you please tell me which ply file on 3dmatch is your data/demo/src.npy & dts.npy, and is my preprocess is correct (read ply->downsample->save npy)? ![Screenshot from 2024-05-13 17-59-38](https://private-user-images.githubusercontent.com/72907719/330011527-841a8e19-6c99-4dec-9c24-9f9de1adfbf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTQ4MTcsIm5iZiI6MTcxNTU5NDUxNywicGF0aCI6Ii83MjkwNzcxOS8zMzAwMTE1MjctODQxYThlMTktNmM5OS00ZGVjLTljMjQtOWY5ZGUxYWRmYmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNGQ0MjhhYTRhODY0MGRlMTM4YTI4YjI3Y2RhN2ViMjJmNmYyM2M2ZTU0ZmNkZjRkNWM0MzAwYzZjZjg5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nFVQPi6O9mq1pUVDXJk9zFbBDu_DNjktH1_p-T_3mk)

@qinzheng93 thanks for your any replay.

**Comment by dspeia** [comment]
@qinzheng93 
thanks for your any reply.

**Comment by CossellCollege** [comment]
> Thank you, I have test GeoTransformer on my own data, the result is very good!

上大校友！不知道你还记不记得这个项目的细节，我没法在我的数据上验证demo.py，想请教你一些问题。

**Comment by jujimeizuo** [comment]
> > [@LinyeLi60](https://github.com/LinyeLi60) I am also interested testing on custom data. Could you give a bit more details how did you manage to finally do it in your case. Thanks.
> 
> Write a new dataset like ThreeDMatchPairKPConvDataset, then every thing will be fine.

Hi bro, did you remember this project? I wanna register my own point cloud(just source.ply and target.ply) on geotransformer too. Could you give me more details? Thanks!

**Comment by hwlagain** [comment]
加1，能详细说说吗
