### ISSUE TITLE
Question about kitti result reproduce.

### ISSUE THREAD

**Issue by vision507** [qinzheng93/GeoTransformer#40]
Hi ,thanks for your amazing work.

However , I have met a problem of kitti dataset result reproduce. I  followed your code to train and test on kitti dataset , but my result seems always lower than the result in your paper. I can achieve Registration recall of 99.8 and RTE 6.8 same as yours ,but my result of  RRE is about  0.33 which is much higher than 0.24 in your paper.

Can you give me some idea of how to reproduce the same result ?

**Comment by qinzheng93** [comment]
How many epochs do you use to train the model?

**Comment by Gardlin** [comment]
160 epochs

**Comment by qinzheng93** [comment]
> 160 epochs

160 could be too long. Try 80-100 epochs.

**Comment by Gardlin** [comment]
I also try test on 60-160 epochs ,but the result always goes near 0.32-0.40, much lower than your paper 0.24.

**Comment by qinzheng93** [comment]
Can you obtain the reported results with the pretrained weights? Do you run `eval.py` for evaluation or just run `test.py`? On odometryKITTI, only the successfully registered pairs are used to compute RRE and RTE, but in `test.py`, all pairs are used. So if you did not run `eval.py`, that could be the reason.

**Comment by Gardlin** [comment]
I run` eval.py` to test  from 60-160 epochs , I saw the same closed issue with me, so it's caused by  floating error? My machine was 3090.
https://github.com/qinzheng93/GeoTransformer/issues/19#issue-1262798694
https://github.com/qinzheng93/GeoTransformer/issues/19#issuecomment-1198319535

**Comment by qinzheng93** [comment]
Can you reproduce the results with the pretrained model? If so, it could be caused by floating error or different random numbers.

**Comment by Gardlin** [comment]
> Can you obtain the reported results with the pretrained weights

I  can't reproduce the results with your pretrained weights.

**Comment by qinzheng93** [comment]
![kitti-results](https://user-images.githubusercontent.com/101389263/198864041-42752f41-0cb4-48f1-8203-673be086538d.png)

I just rerun the evaluation with the pretrained weights and here is the results. I think this could be caused by numeric stability or data preprocessing.
