### ISSUE TITLE
about scale of dataset

### ISSUE THREAD

**Issue by suetme** [qinzheng93/GeoTransformer#41]
Hi, thank you for your excellent work.
I want to know if the scale of my dataset is different from 3DMatch (about 3000-4000 points in a frame, and the bounding box of the point cloud is 60cm * 70cm * 25cm), what parameters do I need to modify to train this model with my dataset? In addition, does my dataset only need to provide source point cloud, target point cloud and transformation matrix?

**Comment by qinzheng93** [comment]
In fact, the hyper-parameters should be determined according to your metrics and your data size.
* If your metric requires the similar precision with 3DMatch (0.1cm for inliers, 20cm for registration), I think you could use the same settings. 
* As your point clouds are smaller, you should avoid too few superpoints after downsampling. In this case, you could reduce the voxel size or use less stages in the backbone.

**Comment by qinzheng93** [comment]
And for the dataset, only source, target and pose are required.
