### ISSUE TITLE
Question about radius search

### ISSUE THREAD

**Issue by Fleurrr** [qinzheng93/GeoTransformer#42]
First of all, thanks for your excellent work!
Radius search in KPConv is quiet slow for large scale point clouds and it usually takes seconds in my own experiments.
Is there a more efficient way for radius search, such as a version that can run on GPU.
Hope to get your answer！

**Comment by qinzheng93** [comment]
I do have a GPU-based KPConv implementation in [Easy-KPConv](https://github.com/qinzheng93/Easy-KPConv). Hope it can help.

And how large are your point clouds? Even on KITTI, the preprocessing speed is still acceptable. If your point clouds are too large, it may be better to use a large voxel size.

**Comment by Fleurrr** [comment]
Thanks for sharing, I'll try it out!
I'm doing something similar to the registration between point cloud maps, the map is large, and the number of points exceeds kitti by several orders of magnitude. I think reckless downsampling may firstly result in loss of local geometric information, and secondly lower resolution of the point cloud should result in a less accurate match between points.

**Comment by Fleurrr** [comment]
> I do have a GPU-based KPConv implementation in [Easy-KPConv](https://github.com/qinzheng93/Easy-KPConv). Hope it can help.
> 
> And how large are your point clouds? Even on KITTI, the preprocessing speed is still acceptable. If your point clouds are too large, it may be better to use a large voxel size.

Thanks for sharing, I'll try it out!
I'm doing something similar to the registration between point cloud maps, the map is large, and the number of points exceeds kitti by several orders of magnitude. I think reckless downsampling may firstly result in loss of local geometric information, and secondly lower resolution of the point cloud should result in a less accurate match between points.

**Comment by qinzheng93** [comment]
I think you could split the map into blocks and use something like retrieval to retrieve a smaller block for registration. Registration between two extremely large point clouds is difficult.

**Comment by Fleurrr** [comment]
> I think you could split the map into blocks and use something like retrieval to retrieve a smaller block for registration. Registration between two extremely large point clouds is difficult.

Thanks for the advice, it makes perfect sense for the work I came to.
