### ISSUE TITLE
How to draw point clouds and correspondences like this?

### ISSUE THREAD

**Issue by Gardlin** [qinzheng93/GeoTransformer#43]
![image](https://user-images.githubusercontent.com/28174084/198256924-0e190a04-3731-4b79-bc4f-db19a850b400.png)
Hi,

Thank you for sharing your excellent work! I have read your paper recently, and I'm wondering how the draw the point clouds and correspondences like yours, which I think is really amazing.
I will be very appreciative if you can give me some idea about how to draw like this.
Thank you very much!

**Comment by qinzheng93** [comment]
I use [vedo](https://vedo.embl.es) to draw the point clouds and the correspondences in this fig. And each point are expanded to a small ball. You can refer to the vedo documents for details.

**Comment by Gardlin** [comment]
Got it,  thanks for your valuable advice.
