### ISSUE TITLE
The resolution in fine matching.

### ISSUE THREAD

**Issue by Hui-design** [qinzheng93/GeoTransformer#44]
Hi, thanks for your amazing work.
I would like to ask why you use the 1/2 resolution in point matching instead of original resolution.  I think this spasity may is the tradeoff of the coarse and accurate registration? But have you tested the result when using the original resolution?

**Comment by qinzheng93** [comment]
The results on the original resolution is worse. I think there could be two reasons.

First, the original resolution is too dense and there is very severe matching ambiguity. In most cases, the features of two points that are close enough to each other are almost the same. As a result, the training target is very ambiguous, making the training more difficult.

Second, if we use the original resolution, there are more points in each patch. This could, first, harm the efficiency, and second, affect the computation of sinkhorn.

**Comment by Hui-design** [comment]
Thank you very much!

**Comment by Hui-design** [comment]
Thank you very much!
