### ISSUE TITLE
The different RR in test.py and eval.py

### ISSUE THREAD

**Issue by Hui-design** [qinzheng93/GeoTransformer#45]
Hello, thank you for you amazing work again.
When I evaluated on 3DMatch, I found the RR reported by test.py and eval.py are very different, what makes this difference?

**Comment by 35p32** [comment]
The definition of whether one pair of point cloud was successfully registered in test and eval stage is different. Check the code.

**Comment by qinzheng93** [comment]
RR in `test.py` is defined as mean error, while RR in `eval.py` is defined as RMSE following Redwood. Use the results from `eval.py` in your paper.

**Comment by Hui-design** [comment]
Thank you for your reply. I agree with that. Apart from the definition of RR, I also find that you remove consecutive frames (may following predator) in eval.py, which also makes the dataset more difficult, resulting in the reduction in RR from "test" to "eval". Is my understanding correct?

**Comment by qinzheng93** [comment]
Yes. The convention of skipping consecutive frames is from 3DMatch.

**Comment by sss752990616** [comment]
Hi @qinzheng93,

Thanks for your great work. As a beginner in this area, I just have one follow-up question, what is the main difference between test.py and eval.py, and why do we need both of them? It looks like they are doing similar things.

**Comment by sss752990616** [comment]
And one more question is that according to my reading of the code for eval.py and test.py, they look like both evaluate the same dataset.  Not sure if my observation is correct.

**Comment by huantuoyushui** [comment]
> Thank you for your reply. I agree with that. Apart from the definition of RR, I also find that you remove consecutive frames (may following predator) in eval.py, which also makes the dataset more difficult, resulting in the reduction in RR from "test" to "eval". Is my understanding correct?

Why skip successive frames here
