### ISSUE TITLE
Is changing variable names of the predecessors a convention?

### ISSUE THREAD

**Issue by liuQuan98** [qinzheng93/GeoTransformer#46]
Thanks for open-sourcing your code. It's an excellent work!

I am currently looking into the kitti dataloader, where you almost renamed all the variables involved, but the essential program logic is not greatly altered from those in OverlapPredator. I know this is a funny question, but I am quite curious on the purpose of doing that. Is this a move to reduce code similarity or just some hidden convention?

**Comment by qinzheng93** [comment]
Yes, the code for KITTI is mainly from D3Feat and Predator. It is for convenience in future modification. The variable names are unified between different datasets so that it is easier to switch between datasets. Will add acknowledgements in the future.
