### ISSUE TITLE
I can't find the following file

### ISSUE THREAD

**Issue by ShuaikangXie** [qinzheng93/GeoTransformer#47]
Hello, the author. When I run your code, I cannot find the following file. I hope you can tell me how to get this file---cloud_bin_0.pth
Similar. pth files. Thank you.

**Comment by qinzheng93** [comment]
Download the data from [PREDATOR](https://github.com/prs-eth/OverlapPredator). Please refer to the data preparation section in the README for more details.

**Comment by ShuaikangXie** [comment]
thank you
