### ISSUE TITLE
How the post in the metadata data is calculated

### ISSUE THREAD

**Issue by linxcan** [qinzheng93/GeoTransformer#49]
Hello, thanks for the work you do, I am very interested in your work. I want to know how the post in the metadata data is calculated when training kitti. I try to use data_odometry_poses to calculate the pose of the adjacent frame, but it seems to be wrong.

**Comment by qinzheng93** [comment]
Following common practice, we refine the pose with ICP. You can refer to [PREDATOR](https://github.com/prs-eth/OverlapPredator) for more details.

**Comment by linxcan** [comment]
Ok, thank you
