### ISSUE TITLE
loss, c_loss and IR is NaN

### ISSUE THREAD

**Issue by rttariverdi67** [qinzheng93/GeoTransformer#54]
Hi, thank you for your grate work.
I am training the model on Waymo flow costum dataset, by costum I extract moving objects, and store them seperately. somewhat looks like Modelnet dataset. number of points in each object is between 0 to 500 or so. I have config set as:
**_C.model.num_points_in_patch = 32
_C.coarse_matching.num_targets = 32
_C.coarse_matching.num_correspondences = 32**

However while training I skip batches that the points has less points than **point_limit**. I don't use augmentation yet, the dataset is huge. what can you sucpect first if I get **loss, c_loss and IR ** NaN, and consider that at first they were not NaN.
![Screenshot from 2022-12-15 20-51-02](https://user-images.githubusercontent.com/53265657/207934757-665e04a3-8e86-4892-b988-13a5e6500a94.png)
![Screenshot from 2022-12-15 21-05-22](https://user-images.githubusercontent.com/53265657/207934966-5af124bc-038a-4d76-8c4f-4f7277f29b5d.png)
![Screenshot from 2022-12-15 21-05-35](https://user-images.githubusercontent.com/53265657/207935004-5d7ccccf-c33c-442a-8379-359a2fec1349.png)

**Comment by rttariverdi67** [comment]
I skip train data as this
![Screenshot from 2022-12-15 21-10-25](https://user-images.githubusercontent.com/53265657/207936061-58fe4af3-57f5-4f1f-a491-6be83421e8af.png)

and val data as this:
![Screenshot from 2022-12-15 21-09-44](https://user-images.githubusercontent.com/53265657/207936244-61d3c159-c039-4dfb-b082-e568a052527a.png)

**Comment by qinzheng93** [comment]
I notice the PIR is normal but IR is NaN, so I think this could be caused by too few points in certain shapes. I suggest you find a case where IR just becomes NaN (the former one is not NaN), and debug on that case.

**Comment by RUiN-jiarun** [comment]
@rttariverdi67 Hi there, I've encountered the similar problems, may I ask how did you get through that? Is it related to the down sample strategy or anything else?
