### ISSUE TITLE
about build geotransformer

### ISSUE THREAD

**Issue by chalth** [qinzheng93/GeoTransformer#55]
Hi, when i build the setup.py , i meet the following errors:

#############################################################################
running build
running build_ext
/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
building 'geotransformer.ext' extension
gcc -pthread -B /home/ch/anaconda3/envs/geotransformer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/include -I/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/include/TH -I/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/ch/anaconda3/envs/geotransformer/include/python3.8 -c geotransformer/extensions/cpu/grid_subsampling/grid_subsampling.cpp -o build/temp.linux-x86_64-cpython-38/geotransformer/extensions/cpu/grid_subsampling/grid_subsampling.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from geotransformer/extensions/cpu/grid_subsampling/../../common/torch_helper.h:3,
                 from geotransformer/extensions/cpu/grid_subsampling/grid_subsampling.h:4,
                 from geotransformer/extensions/cpu/grid_subsampling/grid_subsampling.cpp:2:
/home/ch/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
    5 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
#############################################################################

my env setting is:
cuda: 11.1
gcc/g++ : 9.4.0
 
Do you know how to deal with it?

**Comment by qinzheng93** [comment]
Try this: `pip install ninja`.

**Comment by chalth** [comment]
I installed ninja, but I also met this error

**Comment by yuanl821** [comment]
In the gcc compilation command line, I found this line, '**-I:/usr/local/cuda/include**', and the colon in this line might be the cause of the problem, but I don't know how to fix it.
