### ISSUE TITLE
3DMatch dataset

### ISSUE THREAD

**Issue by DavidBoja** [qinzheng93/GeoTransformer#57]
Hi,

I have a question regarding the D.2. section from the Supplementary material.

Could you please share which 3DMatch files you use for the evaluation?
- Do you use those with overlap > 30%?
- Do you use consecutive pairs of point cloud indices (the original 3DMatch filters the pairs (i,j) with i+1 < j)?

You mention that you use the files from PREDATOR, but PREDATOR has more pairs than the original 3DMatch dataset.
Can you please elaborate?

Thank you in advance for you response.
Hopefully we can clear all this confusion of the registration pairs used in the datasets. Every paper  seems to do it a bit differently.

**Comment by qinzheng93** [comment]
> Do you use those with overlap > 30%?

The point cloud pairs in 3DMatch are with overlap >30%, and those in 3DLoMatch are with overlap between 10% and 30%. And the point cloud pairs during training are with overlap >10%. We use the same data downloaded from [Predator](https://github.com/prs-eth/OverlapPredator). The only modification is that we reorganize the metadata file to our format.

> Do you use consecutive pairs of point cloud indices (the original 3DMatch filters the pairs (i,j) with i+1 < j)?

During training, yes. During testing, consecutive pairs are used for computing FMR and IR (following common practice), but not for RR (following 3DMatch official protocol). You can find the details from `eval.py`.

> You mention that you use the files from PREDATOR, but PREDATOR has more pairs than the original 3DMatch dataset.

I did not notice this though. The testing data we used is the same as Predator.

> Every paper seems to do it a bit differently.

The testing data used by most papers is from [3DMatch](https://3dmatch.cs.princeton.edu) as they provide the fused testing fragments. But the training data is different as not fused fragments are available, but I think it is okay. And I suggest using the data preprocessed by Predator as a standard pipeline as low-overlap pairs are contained.

**Comment by DavidBoja** [comment]
Thank you very much for the quick and thorough response!

>  The point cloud pairs in 3DMatch are with overlap >30%

If you mean that all the pairs from `gt.log` from 3DMatch have an overlap >30%, I don't think its completely accurate (see this [Github issue](https://github.com/prs-eth/OverlapPredator/issues/7))


I would like to focus on Table 8 from the paper from section D.2. from the Supplementary. Maybe I can ask a more concrete question to clear some issues I've been having:
- Do you use the example pair (0,37) from the folder `7-scenes-redkitchen` in the evaluation?
  I'm asking because this example pair is in the `gt.log` in PREDATOR (as can be seen [here](https://github.com/prs-eth/OverlapPredator/blob/main/configs/benchmarks/3DMatch/7-scenes-redkitchen/gt.log#L96)), whilst PREDATOR says the overlap is less than 30% (as can be seen [here](https://github.com/prs-eth/OverlapPredator/blob/main/configs/benchmarks/3DMatch/7-scenes-redkitchen/gt_overlap.log#L37)). Therefore, this example should be eliminated? Do you elimnate it from the evaluation in Table 8?
- Do you use consecutive pairs from 3DMatch in Table 8 to compute the RRE, RTE and RR measures?

Thank you once again for the response. I really appreciate it.

**Comment by qinzheng93** [comment]
>If you mean that all the pairs from gt.log from 3DMatch have an overlap >30%, I don't think its completely accurate (see this https://github.com/prs-eth/OverlapPredator/issues/7)

Yes, but it is okay. This is also mentioned in the paper of Predator. However, I don't really think it is important to strictly split the data around the overlap of 30%. There is little difference between 29.9% and 30.1%. As long as the same data split are used for comparison, the results already make sense.

>Do you use the example pair (0,37) from the folder `7-scenes-redkitchen` in the evaluation?

I make no changes about the data split. Again, this problem is not so important as long as all baselines use the same data split.

>Do you use consecutive pairs from 3DMatch in Table 8 to compute the RRE, RTE and RR measures?

Yes, all pairs are used for evaluation, following common practice.

**Comment by DavidBoja** [comment]
> I don't really think it is important to strictly split the data around the overlap of 30%. 

I agree, this should be insignificant. However, I just want to point out that when I compute the overlap ratio using the PREDATOR [code](https://github.com/prs-eth/OverlapPredator/blob/main/scripts/cal_overlap.py) on full point clouds (PREDATOR computes the overlap on voxel-downsampled point clouds), some overlaps differ drastically. More concretely, there are now 280 examples with overlap <30%, the lowest of them having 4% of overlap. There are only 10 pairs with <10% overlap, so as you've said this is not a big issue, but surely something to know.

> I make no changes about the data split. Again, this problem is not so important as long as all baselines use the same data split.

I agree, the most important thing is that all the methods have a consistent comparison.

I am closing this issue since you answered all my questions. Thank you once again. Best wishes! :)
