### ISSUE TITLE
Running demo on 3DMatch test set

### ISSUE THREAD

**Issue by amir-opal** [qinzheng93/GeoTransformer#58]
When I want to run the demo on two other samples from test set of 3DMatch dataset, it seems that the result is not wright. I get one fixed value of inlier ratio for two random samples. As RANSAC has a random nature, the produced results should be a little different. I should say that I preprocessed the data and changed their formats to numpy arrays.

**Comment by qinzheng93** [comment]
Do you set `--method=ransac`? RANSAC is not used by default.

**Comment by amir-opal** [comment]
No. I do not use RANSAC as part of the algorithm. I only use it to evaluate the performance of the algorithm in registration of two point clouds. The inlier ratio I get when I run demo on two samples from test set is much less than the inlier ratio I get from running demo on two available samples. Also, I get a fixed value for inlier ratio when I run on samples from test set.

**Comment by qinzheng93** [comment]
There was a bug in `demo.py` as in this [issue](https://github.com/qinzheng93/GeoTransformer/issues/51). Do you use the latest code?
