### ISSUE TITLE
Question about SuperPoint Matching

### ISSUE THREAD

**Issue by zhil-chen** [qinzheng93/GeoTransformer#6]
Thank you for your wonderful work!
It's confused me that why GeoTransformer randomly selects ground truth node correspondences when training instead of using topk node correspondences.
Looking forward your reply.

**Comment by zhil-chen** [comment]
Besides, I want to know which features and points do you use when your estimator is RANSAC-50k.

**Comment by qinzheng93** [comment]
1. Training with topk node correspondences could make the model lean to predicting too much negatives. For this reason, we only use ground-truth node correspondences during training.
2. We directly use the correspondences for RANSAC, i.e., `registration_ransac_based_on_correspondence` in open3d. See `eval.py` for more details.

**Comment by zhil-chen** [comment]
Thank you for your reply.
