### ISSUE TITLE
How to get the pth files.

### ISSUE THREAD

**Issue by stick-cpu** [qinzheng93/GeoTransformer#63]
Hello, when I run the program. I came accross a problem. I have the point cloud files which is the ply files, while the file in code is pth forms.How can I get the pth files.Thank you for you help.

**Comment by PANFEI-CHENG** [comment]
Hello, I have encountered the same problem. Have you solve it?

**Comment by cmy76** [comment]
Try this
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/data.zip
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/weights.zip
unzip data.zip
unzip weights.zip
rm data.zip
rm weights.zip

**Comment by PANFEI-CHENG** [comment]
> Try this wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/data.zip wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/weights.zip unzip data.zip unzip weights.zip rm data.zip rm weights.zip

Thank you for your help!

**Comment by stick-cpu** [comment]
> Try this wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/data.zip wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/weights.zip unzip data.zip unzip weights.zip rm data.zip rm weights.zip

Thank you for your help!
