### ISSUE TITLE
3DMatch: RRE does not match between val and train

### ISSUE THREAD

**Issue by Sigura** [qinzheng93/GeoTransformer#68]
If you will fill `data_dict['transform'] = np.eye(4).astype(np.float32)` on validation you will see real result.

Same in demo.

<img width="1069" alt="Screenshot 2023-05-19 at 10 00 43" src="https://github.com/qinzheng93/GeoTransformer/assets/428500/dab75c38-b819-4093-a4e7-85fc9362ac04">

Same on 69

**Comment by qinzheng93** [comment]
Why do you set the transform to identity matrix?

**Comment by Sigura** [comment]
Sorry looks like it works anyway.... It make me crazy.

**Comment by Sigura** [comment]
Sorry looks like it works anyway.... It make me crazy.

**Comment by huantuoyushui** [comment]
> Why do you set the transform to identity matrix?

**Comment by huantuoyushui** [comment]
> Why do you set the transform to identity matrix?

I didn't set gt as the identity matrix, but I also got such a result

**Comment by huantuoyushui** [comment]
> Sorry looks like it works anyway.... It make me crazy.

I'm getting this result as well, did you fix the issue？
