### ISSUE TITLE
Maybe there is some careless mistake here

### ISSUE THREAD

**Issue by PANFEI-CHENG** [qinzheng93/GeoTransformer#71]
Is here something wrong at eval.py L125?
if args.num_corr is not None and corr_scores.shape[0] > engine.args.num_corr:#如果指定了最大匹配点数，则挑选排名靠前的点
                sel_indices = np.argsort(-corr_scores)[: args.num_corr]
                ref_corr_points = ref_corr_points[sel_indices]
                src_corr_points = src_corr_points[sel_indices]
                corr_scores = corr_scores[sel_indices]
 Exception has occurred: NameError
name 'engine' is not defined
Maybe there is some careless mistake here

**Comment by qinzheng93** [comment]
Please install the required library following the README.
