### ISSUE TITLE
How to operate the model to rotate only around the z-axis instead of in any direction

### ISSUE THREAD

**Issue by mcmingchang** [qinzheng93/GeoTransformer#74]
How to operate the model to rotate only around the z-axis instead of in any direction
![微信图片_20230721110805](https://github.com/qinzheng93/GeoTransformer/assets/37234299/674be3d1-b596-4b93-b271-4ef78e9613c0)

**Comment by qinzheng93** [comment]
Please refer to this [function](https://github.com/qinzheng93/GeoTransformer/blob/e7a135af4c318ff3b8d7f6c963df094d7e4ea540/geotransformer/transforms/functional.py#L58).
