### ISSUE TITLE
How should I train my dataset?

### ISSUE THREAD

**Issue by wyaimyj** [qinzheng93/GeoTransformer#75]
Hello, I would like to use your model to train on my own dataset. My dataset consists of point clouds from different viewpoints of a statue. However, I do not have the corresponding rotation and translation matrices between the point clouds pairwise. How can I address this issue? Thank you!

**Comment by joker-lb7** [comment]
I have a similar problem, I don't know how to calculate the overlap rate of homemade datasets, can you help? Thank you

**Comment by qinzheng93** [comment]
Please refer to #34.
