### ISSUE TITLE
can't find the correct file

### ISSUE THREAD

**Issue by jeff0908** [qinzheng93/GeoTransformer#76]
Thanks for sharing the open source on the github
Here's a question when i run this command "CUDA_VISIBLE_DEVICES=0 python trainval.py" 
And it can't read right file in the project  "FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/kuan/GeoTransformer/data/3DMatch/data/train/rgbd-scenes-v2-scene_01/cloud_bin_2.pth'"
i just download the data which is mentioned in issue #63 and it doesn't exist any file named "cloud_bin_2.pth"
my data route is "C:\kuan\GeoTransformer\data\3DMatch\data\train\rgbd-scenes-v2-scene_01\poses\cloud_bin_0.txt"   or  "C:\kuan\GeoTransformer\data\3DMatch\data\train\rgbd-scenes-v2-scene_01\fragments\cloud_bin_0.ply"

**Comment by qinzheng93** [comment]
It seems that the latest data remove the preprocessed pth files. To generate the pth files, use this [function](https://github.com/qinzheng93/GeoTransformer/blob/e7a135af4c318ff3b8d7f6c963df094d7e4ea540/geotransformer/utils/open3d.py#L57) to downsample the point clouds by 2.5cm and save it to pth.
