### ISSUE TITLE
No Module called geotransformer.ext

### ISSUE THREAD

**Issue by singhbino3d** [qinzheng93/GeoTransformer#80]
when I run steup.py build develop, the process runs but after trying to run the next step i get an error saying no module named geotransformer.ext found

**Comment by Frq-F** [comment]
Hello, I have also encountered this issue. Have you resolved it？

**Comment by singhbino3d** [comment]
Hello, I managed to solve it!
if you are using an isolated container or an environment, are you running the commands in the same or not?
because this module adds to the system path.

Since I was using two different containers, was giving me that error. 
Hope this helps!
